-- 薪资项目表增加编辑类型, 支持可编辑公式项目
ALTER TABLE T_HRSAL_ITEM ADD C_EDITTYPE CHAR(1) DEFAULT '0' NOT NULL;

COMMENT ON COLUMN T_HRSAL_ITEM.C_BELONG IS '机构';
COMMENT ON COLUMN T_HRSAL_ITEM.C_ID IS '内部ID';
COMMENT ON COLUMN T_HRSAL_ITEM.C_NO IS '项目号';
COMMENT ON COLUMN T_HRSAL_ITEM.C_NAME IS '使用名称';
COMMENT ON COLUMN T_HRSAL_ITEM.C_ONDATE IS '启用日期';
COMMENT ON COLUMN T_HRSAL_ITEM.C_DOWNDATE IS '停用日期';
COMMENT ON COLUMN T_HRSAL_ITEM.C_ACCOUNT_DEBIT IS '来源科目';
COMMENT ON COLUMN T_HRSAL_ITEM.C_ACCOUNT_CREDIT IS '去向科目';
COMMENT ON COLUMN T_HRSAL_ITEM.C_FLAG IS '方向：发放(1)、不计入总额(0)、扣回(-1)';
COMMENT ON COLUMN T_HRSAL_ITEM.C_TYPE IS '固定类别：工资项目(WG)、社保项目(SG)、福利项目(WF)、代扣项目(DK)、对消项目(平帐项目PZ)';
COMMENT ON COLUMN T_HRSAL_ITEM.C_PRINT IS '打印：显示打印(1)、只显示(0)';
COMMENT ON COLUMN T_HRSAL_ITEM.C_FORMULA IS '公式';
COMMENT ON COLUMN T_HRSAL_ITEM.C_EDITTYPE IS '编辑类型：不可编辑(0)、可编辑(1)';

ALTER TABLE T_HRSAL_ITEM ADD (CONSTRAINT CHK_HRSAL_ITEM_EDITTYPE CHECK (C_EDITTYPE IN ('0','1')));
ALTER TABLE T_HRSAL_ITEM ADD (CONSTRAINT CHK_HRSAL_ITEM_FLAG CHECK (C_FLAG IN (-1,0,1)));
ALTER TABLE T_HRSAL_ITEM ADD (CONSTRAINT CHK_HRSAL_ITEM_PRINT CHECK (C_PRINT IN ('0','1')));
ALTER TABLE T_HRSAL_ITEM ADD (CONSTRAINT CHK_HRSAL_ITEM_TYPE CHECK (C_TYPE IN ('WG','SG','WF','DK','PZ')));
UPDATE T_HRSAL_ITEM SET C_EDITTYPE=CASE WHEN C_FORMULA IS NULL THEN '1' ELSE '0' END;
COMMIT;

-- 人员表增加缴金工龄相关字段:
ALTER TABLE T_PERSONAL ADD C_PAYSOCIALINS_INIT NUMBER(3) DEFAULT 0 NOT NULL;
ALTER TABLE T_PERSONAL ADD C_PAYSOCIALINS_ADJ NUMBER(3) DEFAULT 0 NOT NULL;
COMMENT ON COLUMN T_PERSONAL.C_PAYSOCIALINS_INIT IS '92年之前的工龄(单位为月，社保体系建立之前的工龄，系统按缴金工龄处理)';
COMMENT ON COLUMN T_PERSONAL.C_PAYSOCIALINS_ADJ IS '92年之后使用薪资系统之前的缴金工龄';
COMMIT;

-- 2010-1-25: 薪资项目表增加备注字段
ALTER TABLE T_HRSAL_ITEM ADD C_COMMENT VARCHAR2(255);
COMMENT ON COLUMN T_HRSAL_ITEM.C_COMMENT IS '备注';

-- 2011-2-17: 薪资凭证保存速度调优
-- 1) 增加凭证级检查存储过程SP_HRSAL_FACT
-- 2) 增加T_HRSAL_FIXONLINE表索引, 加快存储过程SP_HRSAL_FACT中查询语句的执行速度
CREATE OR REPLACE PROCEDURE SP_HRSAL_FACT(BRANCHID IN NUMBER,
                                          HDNO     IN VARCHAR2) IS
  -- 检查凭证(BRANCHID+HDNO)是否有非法记录:
  -- 1. 人员是否有重复: 一张凭证(T_HRSAL_FACTDT)中某一C_PERSON对应的C_NO唯一
  -- 2. 公式项目的数值等价性: 有固定项目先验证有没有公式,没有公式必须和当前有效的项目值相等
  V_F1           NUMBER;
  V_F2           NUMBER;
  V_BELONG       NUMBER;
  V_PERSON       NUMBER;
  V_WORKERID     VARCHAR2(40);
  V_PERSONALNAME VARCHAR2(40);
  V_COUNT        NUMBER;
  V_NO           NUMBER;
  V_ITEM         NUMBER;
  V_ITEMNO       VARCHAR2(16);
  V_ITEMNAME     VARCHAR2(30);
  V_AMOUNT1      NUMBER(18,4);
  V_AMOUNT2      NUMBER(18,4);
  CURSOR C1 IS
    SELECT T1.C_BELONG, T1.C_PERSON, T2.C_WORKERID, T2.C_PERSONALNAME, COUNT(*)
      FROM (SELECT C_BELONG, C_PERSON, C_NO, COUNT(*) FROM T_HRSAL_FACTDT WHERE C_HDNO = HDNO AND C_BELONG = BRANCHID GROUP BY C_BELONG, C_PERSON, C_NO ORDER BY C_NO) T1, T_PERSONAL T2
      WHERE T1.C_PERSON=T2.C_PERSONALID AND T1.C_BELONG=T2.C_BELONG GROUP BY T1.C_BELONG, T1.C_PERSON, T2.C_WORKERID, T2.C_PERSONALNAME HAVING COUNT(*) > 1;
  CURSOR C2 IS
    SELECT T1.C_NO, T1.C_PERSON, T4.C_PERSONALNAME, T1.C_ITEM, T5.C_NO, T5.C_NAME, T1.C_AMOUNT, T2.C_AMOUNT
      FROM T_HRSAL_FACTDT T1 INNER JOIN T_HRSAL_FACT T3 ON T1.C_BELONG = T3.C_BELONG AND T1.C_HDNO = T3.C_NO
	    INNER JOIN T_PERSONAL T4 ON T1.C_BELONG = T4.C_BELONG AND T1.C_PERSON = T4.C_PERSONALID
		INNER JOIN T_HRSAL_ITEM T5 ON T1.C_BELONG = T5.C_BELONG AND T1.C_ITEM = T5.C_ID
		LEFT OUTER JOIN T_HRSAL_FIXONLINE T2 ON T1.C_BELONG = T2.C_BELONG AND T1.C_PERSON = T2.C_PERSON AND T1.C_ITEM = T2.C_ITEM AND T2.C_ONDATE <= T3.C_DATE AND T2.C_DOWNDATE > T3.C_DATE
    WHERE T1.C_BELONG=BRANCHID AND T1.C_HDNO=HDNO AND T1.C_AMOUNT <> T2.C_AMOUNT;
BEGIN
  -- 1. 人员是否有重复
  V_F1 := 1;
  OPEN C1;
  FETCH C1 INTO V_BELONG, V_PERSON, V_WORKERID, V_PERSONALNAME, V_COUNT;
  IF C1%NOTFOUND THEN
    V_F1 := 0;
  END IF;
  CLOSE C1;
  IF V_F1 = 1 THEN
    RAISE_APPLICATION_ERROR(-20003, '人员' || V_PERSONALNAME || '在本薪资凭证中重复发放!');
  END IF;

  -- 2. 公式项目的数值等价性: 有固定项目先验证有没有公式,没有公式必须和当前有效的项目值相等
  V_F2 := 1;
  OPEN C2;
  FETCH C2 INTO V_NO, V_PERSON, V_PERSONALNAME, V_ITEM, V_ITEMNO, V_ITEMNAME, V_AMOUNT1, V_AMOUNT2;
  IF C2%NOTFOUND THEN
    V_F2 := 0;
  END IF;
  CLOSE C2;
  IF V_F2 = 1 THEN
    RAISE_APPLICATION_ERROR(-20003, '第' || V_NO || '行人员[' || V_PERSONALNAME || ']项目[' || V_ITEMNAME || ']的发放值=' || V_AMOUNT1 || ',与该人员的有效固定项目值[' || V_AMOUNT2 || ']不一致!');
  END IF;
END SP_HRSAL_FACT;
/

CREATE INDEX IDX_HRSAL_FIXONLINE ON T_HRSAL_FIXONLINE (C_BELONG, C_PERSON, C_ITEM) LOGGING NOPARALLEL;

-- 2011-3-8: 增加T_HRSAL_TEMPLATEIX和T_HRSAL_FACTIX表, 支持薪资模板和凭证中自定义项目顺序
CREATE TABLE T_HRSAL_TEMPLATEIX
(
  C_BELONG  NUMBER(18)                          NOT NULL,
  C_HD      NUMBER(18)                          NOT NULL,
  C_ITEM    NUMBER(18)                          NOT NULL,
  C_NO      NUMBER(4)                           NOT NULL,
  CONSTRAINT PK_HRSAL_TEMPLATEIX PRIMARY KEY (C_BELONG, C_HD, C_ITEM)
) LOGGING NOCACHE NOPARALLEL MONITORING;
-- 外键
ALTER TABLE T_HRSAL_TEMPLATEIX ADD (CONSTRAINT FK_HRSAL_TIXBRANCH FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH (C_BRANCHID));
ALTER TABLE T_HRSAL_TEMPLATEIX ADD (CONSTRAINT FK_HRSAL_TIXHD FOREIGN KEY (C_BELONG, C_HD) REFERENCES T_HRSAL_TEMPLATE (C_BELONG,C_ID));
ALTER TABLE T_HRSAL_TEMPLATEIX ADD (CONSTRAINT FK_HRSAL_TIXITEM FOREIGN KEY (C_BELONG, C_ITEM) REFERENCES T_HRSAL_ITEM (C_BELONG,C_ID));
-- 数据初始化
INSERT INTO T_HRSAL_TEMPLATEIX(C_BELONG, C_HD, C_ITEM, C_NO) SELECT C_BELONG, C_HD, C_ITEM, ROW_NUMBER() OVER (PARTITION BY C_HD ORDER BY C_ITEM ASC) C_NO FROM 
  (SELECT DISTINCT T1.C_BELONG, T1.C_HD, T1.C_ITEM, T2.C_NO FROM T_HRSAL_TEMPLATEDT T1, T_HRSAL_ITEM T2 
  WHERE T1.C_BELONG = T2.C_BELONG AND T1.C_ITEM = T2.C_ID ORDER BY T1.C_HD, T2.C_NO) T;
-- 增加薪资模板表外键
ALTER TABLE T_HRSAL_TEMPLATEDT ADD (CONSTRAINT FK_HRSAL_TDTIX FOREIGN KEY (C_BELONG, C_HD, C_ITEM) REFERENCES T_HRSAL_TEMPLATEIX (C_BELONG,C_HD,C_ITEM));

CREATE TABLE T_HRSAL_FACTIX
(
  C_BELONG  NUMBER(18)                          NOT NULL,
  C_HDNO    VARCHAR2(30)                        NOT NULL,
  C_ITEM    NUMBER(18)                          NOT NULL,
  C_NO      NUMBER(4)                           NOT NULL,
  CONSTRAINT PK_HRSAL_FACTIX PRIMARY KEY (C_BELONG, C_HDNO, C_ITEM)
) LOGGING NOCACHE NOPARALLEL MONITORING;
-- 外键
ALTER TABLE T_HRSAL_FACTIX ADD (CONSTRAINT FK_HRSAL_FIXBRANCH FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH (C_BRANCHID));
ALTER TABLE T_HRSAL_FACTIX ADD (CONSTRAINT FK_HRSAL_FIXHD FOREIGN KEY (C_BELONG, C_HDNO) REFERENCES T_HRSAL_FACT (C_BELONG,C_NO));
ALTER TABLE T_HRSAL_FACTIX ADD (CONSTRAINT FK_HRSAL_FIXITEM FOREIGN KEY (C_BELONG, C_ITEM) REFERENCES T_HRSAL_ITEM (C_BELONG,C_ID));
-- 数据初始化
INSERT INTO T_HRSAL_FACTIX(C_BELONG, C_HDNO, C_ITEM, C_NO) SELECT C_BELONG, C_HDNO, C_ITEM, ROW_NUMBER() OVER (PARTITION BY C_HDNO ORDER BY C_ITEM ASC) C_NO FROM 
  (SELECT DISTINCT T1.C_BELONG, T1.C_HDNO, T1.C_ITEM, T2.C_NO FROM T_HRSAL_FACTDT T1, T_HRSAL_ITEM T2 
  WHERE T1.C_BELONG = T2.C_BELONG AND T1.C_ITEM = T2.C_ID ORDER BY T1.C_HDNO, T2.C_NO) T;
-- 增加薪资凭证表外键
ALTER TABLE T_HRSAL_FACTDT ADD (CONSTRAINT FK_HRSAL_FDTIX FOREIGN KEY (C_BELONG, C_HDNO, C_ITEM) REFERENCES T_HRSAL_FACTIX (C_BELONG,C_HDNO,C_ITEM));
